dbt_example:
  outputs:
    dev:
      catalog: dbt_example_dev
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP') }}"
      schema: default
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
    prod:
      catalog: dbt_example_prod
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP') }}"
      schema: default
      threads: 4
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
