sources:
  - name: dbt_source
    database: dbt_example_dev
    schema: source
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_returns
      - name: fact_sales
